domain_path: C:\Repositorios\edemetCampos\StyxFreeRTOS\platform\export\platform\sw\freertos_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
